version: '3.1'
services:
  openpbl:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - openpbl-db
  openpbl-db:
    restart: always
    image: mysql:8.0.25
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /usr/local/docker/openpbl-mysql:/var/lib/mysql